services:
  backend:
    build:
      context: ./docker/php
    container_name: university-backend
    volumes:
      - ./src/backend:/var/www/html
    depends_on:
      - db
      - redis
    networks:
      - university
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8081

  frontend:
    image: node:20
    container_name: university-frontend
    working_dir: /app
    volumes:
      - ./src/frontend:/app
      - /app/node_modules    # üëà –∑–±–µ—Ä—ñ–≥–∞—î–º–æ node_modules –≤—Å–µ—Ä–µ–¥–∏–Ω—ñ –∫–æ–Ω—Ç–µ–π–Ω–µ—Ä–∞
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
    networks:
      - university


  web:
    image: nginx:latest
    container_name: university-nginx
    ports:
      - "8081:80"
    volumes:
      - ./src/backend:/var/www/html
      - ./src/frontend/dist:/var/www/html/frontend
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - university

  db:
    image: postgres:15-alpine
    container_name: university-db
    environment:
      POSTGRES_DB: university
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - university

  redis:
    image: redis:alpine
    container_name: university-redis
    ports:
      - "6379:6379"
    networks:
      - university

volumes:
  pgdata:

networks:
  university:
